const List<String> mandatoryValidators = [
  'anti_corruption',
  'authorship',
  'boundaries',
  'build',
  'console_logs',
  'features_architecture',
  'forbidden_files',
  'ghost',
  'hardcoding',
  'inline_comments',
  'linting',
  'mutation',
  'no_spanish',
  'testing',
];
